# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pwm_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpwm_proto.proto\x12\x08pwm_link\"1\n\nPwmCommand\x12\x10\n\x08left_pwm\x18\x01 \x01(\x11\x12\x11\n\tright_pwm\x18\x02 \x01(\x11\"O\n\x11JetsonToEspPacket\x12+\n\x0bpwm_command\x18\x01 \x01(\x0b\x32\x14.pwm_link.PwmCommandH\x00\x42\r\n\x0bpacket_type\"\x1a\n\nLogMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"O\n\x11\x45spToJetsonPacket\x12+\n\x0blog_message\x18\x01 \x01(\x0b\x32\x14.pwm_link.LogMessageH\x00\x42\r\n\x0bpacket_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pwm_proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PWMCOMMAND._serialized_start=29
  _PWMCOMMAND._serialized_end=78
  _JETSONTOESPPACKET._serialized_start=80
  _JETSONTOESPPACKET._serialized_end=159
  _LOGMESSAGE._serialized_start=161
  _LOGMESSAGE._serialized_end=187
  _ESPTOJETSONPACKET._serialized_start=189
  _ESPTOJETSONPACKET._serialized_end=268
# @@protoc_insertion_point(module_scope)
